import { Box, Card, CardMedia, Container, Grid, Typography, useMediaQuery } from "@mui/material";
import { useTheme } from "@mui/material/styles";
import { useNavigate, useParams } from "react-router-dom";
import Catalog from "../assets/logo/catalog.png";
import Customer from "../assets/logo/customer.png";
import OmniChannel from "../assets/logo/omnichannel.png";
import Order from "../assets/logo/order.jpg";
import Pos from "../assets/logo/pos.png";
import Report from "../assets/logo/reports.png";
import Social from "../assets/logo/social.jpg";
import Wms from "../assets/logo/wms.png";
import React from "react";

interface ArticleProps {
  title: string;
  image: string;
  description: string;
  content: string[];
}
const omnichannelProducts: ArticleProps[] = [
  {
    title: "Omnichannel retail software",
    description:
      "Comprehensive software solutions for integrating and synchronizing sales channels.",
    image: OmniChannel,
    content: [
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum suscipit, eos accusamus recusandae nemo voluptas consequuntur perspiciatis iusto obcaecati possimus temporibus quia doloribus voluptatem quas. Iusto nisi architecto, quibusdam dolor ipsum inventore ut alias atque! Nisi, iusto fuga ullam atque praesentium illum, sunt dolores minima quod laborum consequatur velit ipsa aliquid placeat! Laborum inventore recusandae aut a dolorem! Explicabo dolorem iusto exercitationem deserunt molestiae recusandae suscipit quae quaerat dolor inventore cumque delectus maxime consequatur sequi, temporibus nam aspernatur eum voluptas tenetur voluptate a natus impedit ea? Doloremque facilis reprehenderit distinctio labore libero aspernatur obcaecati velit iusto ipsa. Ea error atque, blanditiis ducimus possimus ipsam, similique aut qui earum expedita illum tenetur cumque laudantium cum dicta voluptatum optio. Modi illo amet pariatur omnis sapiente, laboriosam fugiat blanditiis labore laudantium quasi illum ratione suscipit, unde cumque accusantium animi dicta! Totam possimus accusantium minus vero illum suscipit reiciendis, cumque debitis quisquam placeat, ducimus, exercitationem harum quia quo pariatur quaerat voluptas dicta officiis ex est. Esse nihil obcaecati minima deleniti vel, dolore, maxime a quis ab reprehenderit ut illum, sapiente in! Nobis, autem quasi optio id illo facilis, fugit unde harum corporis dicta placeat! Quos nulla veniam saepe earum ratione maxime quasi magnam animi maiores? Ullam sequi, soluta eum dolorum possimus laudantium tempore, inventore dolor nemo quos, eligendi reiciendis labore magni! Voluptatem facere ratione rerum tempore labore suscipit itaque ipsum architecto eius! Possimus, minima odio. Nostrum quos eligendi, voluptate explicabo molestiae error aliquid obcaecati doloremque distinctio vel amet quam dignissimos officiis eum maiores saepe.",
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere velit totam doloremque? Atque accusamus hic non quidem eligendi deleniti ipsa fuga laudantium tempora laborum dolore id ab provident ad aliquam repudiandae, nostrum dolores. Deleniti consectetur tempore accusantium iste ducimus nesciunt distinctio, inventore doloribus totam quam quasi, excepturi facere culpa quas officiis iure qui eos. Corrupti nostrum aut ipsam officia consequatur assumenda possimus. Totam ut natus deleniti dolores, adipisci, molestias sequi optio recusandae illum eaque cumque numquam animi velit quibusdam quo ea nesciunt reprehenderit? Quam enim tempora in. Fuga ex odit laudantium repellendus temporibus tempora, culpa, facere laboriosam dignissimos inventore sunt minima, non tempore. Atque nobis dolorem deleniti fugit, obcaecati odit placeat eaque esse aliquam qui sint ullam quisquam similique, perspiciatis nemo possimus neque repellat itaque minus ipsam! Consequatur vel laboriosam deserunt, possimus id veritatis non porro facilis nam impedit perferendis minus libero quam! Officia temporibus eius, asperiores earum ullam necessitatibus suscipit! Sint omnis culpa fugit esse dolores voluptates error, sed optio animi accusamus maxime, quos odit similique, alias ab rem odio inventore iste dolore sequi iusto. Ullam dolor aliquam quo, ab necessitatibus reiciendis vitae, beatae fuga iste modi saepe consectetur repellat quia error vel iure, qui asperiores tenetur atque! Autem delectus similique aliquam possimus rem. Mollitia quibusdam, totam harum necessitatibus aut accusamus amet quod doloribus natus, error blanditiis voluptates, cum rem ratione eveniet culpa unde animi! Cupiditate, harum quis autem atque aperiam doloremque, enim, aspernatur vero ea esse rerum eum. Odio laborum sequi aliquam amet rerum distinctio quaerat dicta, placeat aut repudiandae expedita ipsum quam consequatur architecto enim optio sint atque praesentium sunt sapiente ea unde! Quod qui maxime unde beatae quibusdam, eaque doloribus laborum tempore et! Ipsum vel perferendis voluptatum exercitationem, officia odit consequatur magni hic consectetur adipisci libero, eos aspernatur, nulla amet possimus eaque voluptate veniam cumque tempore?",
    ],
  },
  {
    title: "Customer engagement platforms",
    description: "Tools and platforms for personalized and interactive customer experiences.",
    image: Customer,
    content: [
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum suscipit, eos accusamus recusandae nemo voluptas consequuntur perspiciatis iusto obcaecati possimus temporibus quia doloribus voluptatem quas. Iusto nisi architecto, quibusdam dolor ipsum inventore ut alias atque! Nisi, iusto fuga ullam atque praesentium illum, sunt dolores minima quod laborum consequatur velit ipsa aliquid placeat! Laborum inventore recusandae aut a dolorem! Explicabo dolorem iusto exercitationem deserunt molestiae recusandae suscipit quae quaerat dolor inventore cumque delectus maxime consequatur sequi, temporibus nam aspernatur eum voluptas tenetur voluptate a natus impedit ea? Doloremque facilis reprehenderit distinctio labore libero aspernatur obcaecati velit iusto ipsa. Ea error atque, blanditiis ducimus possimus ipsam, similique aut qui earum expedita illum tenetur cumque laudantium cum dicta voluptatum optio. Modi illo amet pariatur omnis sapiente, laboriosam fugiat blanditiis labore laudantium quasi illum ratione suscipit, unde cumque accusantium animi dicta! Totam possimus accusantium minus vero illum suscipit reiciendis, cumque debitis quisquam placeat, ducimus, exercitationem harum quia quo pariatur quaerat voluptas dicta officiis ex est. Esse nihil obcaecati minima deleniti vel, dolore, maxime a quis ab reprehenderit ut illum, sapiente in! Nobis, autem quasi optio id illo facilis, fugit unde harum corporis dicta placeat! Quos nulla veniam saepe earum ratione maxime quasi magnam animi maiores? Ullam sequi, soluta eum dolorum possimus laudantium tempore, inventore dolor nemo quos, eligendi reiciendis labore magni! Voluptatem facere ratione rerum tempore labore suscipit itaque ipsum architecto eius! Possimus, minima odio. Nostrum quos eligendi, voluptate explicabo molestiae error aliquid obcaecati doloremque distinctio vel amet quam dignissimos officiis eum maiores saepe.",
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere velit totam doloremque? Atque accusamus hic non quidem eligendi deleniti ipsa fuga laudantium tempora laborum dolore id ab provident ad aliquam repudiandae, nostrum dolores. Deleniti consectetur tempore accusantium iste ducimus nesciunt distinctio, inventore doloribus totam quam quasi, excepturi facere culpa quas officiis iure qui eos. Corrupti nostrum aut ipsam officia consequatur assumenda possimus. Totam ut natus deleniti dolores, adipisci, molestias sequi optio recusandae illum eaque cumque numquam animi velit quibusdam quo ea nesciunt reprehenderit? Quam enim tempora in. Fuga ex odit laudantium repellendus temporibus tempora, culpa, facere laboriosam dignissimos inventore sunt minima, non tempore. Atque nobis dolorem deleniti fugit, obcaecati odit placeat eaque esse aliquam qui sint ullam quisquam similique, perspiciatis nemo possimus neque repellat itaque minus ipsam! Consequatur vel laboriosam deserunt, possimus id veritatis non porro facilis nam impedit perferendis minus libero quam! Officia temporibus eius, asperiores earum ullam necessitatibus suscipit! Sint omnis culpa fugit esse dolores voluptates error, sed optio animi accusamus maxime, quos odit similique, alias ab rem odio inventore iste dolore sequi iusto. Ullam dolor aliquam quo, ab necessitatibus reiciendis vitae, beatae fuga iste modi saepe consectetur repellat quia error vel iure, qui asperiores tenetur atque! Autem delectus similique aliquam possimus rem. Mollitia quibusdam, totam harum necessitatibus aut accusamus amet quod doloribus natus, error blanditiis voluptates, cum rem ratione eveniet culpa unde animi! Cupiditate, harum quis autem atque aperiam doloremque, enim, aspernatur vero ea esse rerum eum. Odio laborum sequi aliquam amet rerum distinctio quaerat dicta, placeat aut repudiandae expedita ipsum quam consequatur architecto enim optio sint atque praesentium sunt sapiente ea unde! Quod qui maxime unde beatae quibusdam, eaque doloribus laborum tempore et! Ipsum vel perferendis voluptatum exercitationem, officia odit consequatur magni hic consectetur adipisci libero, eos aspernatur, nulla amet possimus eaque voluptate veniam cumque tempore?",
    ],
  },
  {
    title: "Point-of-sale (POS) systems",
    description: "Advanced systems connecting physical and online stores for real-time management.",
    image: Pos,
    content: [
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum suscipit, eos accusamus recusandae nemo voluptas consequuntur perspiciatis iusto obcaecati possimus temporibus quia doloribus voluptatem quas. Iusto nisi architecto, quibusdam dolor ipsum inventore ut alias atque! Nisi, iusto fuga ullam atque praesentium illum, sunt dolores minima quod laborum consequatur velit ipsa aliquid placeat! Laborum inventore recusandae aut a dolorem! Explicabo dolorem iusto exercitationem deserunt molestiae recusandae suscipit quae quaerat dolor inventore cumque delectus maxime consequatur sequi, temporibus nam aspernatur eum voluptas tenetur voluptate a natus impedit ea? Doloremque facilis reprehenderit distinctio labore libero aspernatur obcaecati velit iusto ipsa. Ea error atque, blanditiis ducimus possimus ipsam, similique aut qui earum expedita illum tenetur cumque laudantium cum dicta voluptatum optio. Modi illo amet pariatur omnis sapiente, laboriosam fugiat blanditiis labore laudantium quasi illum ratione suscipit, unde cumque accusantium animi dicta! Totam possimus accusantium minus vero illum suscipit reiciendis, cumque debitis quisquam placeat, ducimus, exercitationem harum quia quo pariatur quaerat voluptas dicta officiis ex est. Esse nihil obcaecati minima deleniti vel, dolore, maxime a quis ab reprehenderit ut illum, sapiente in! Nobis, autem quasi optio id illo facilis, fugit unde harum corporis dicta placeat! Quos nulla veniam saepe earum ratione maxime quasi magnam animi maiores? Ullam sequi, soluta eum dolorum possimus laudantium tempore, inventore dolor nemo quos, eligendi reiciendis labore magni! Voluptatem facere ratione rerum tempore labore suscipit itaque ipsum architecto eius! Possimus, minima odio. Nostrum quos eligendi, voluptate explicabo molestiae error aliquid obcaecati doloremque distinctio vel amet quam dignissimos officiis eum maiores saepe.",
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere velit totam doloremque? Atque accusamus hic non quidem eligendi deleniti ipsa fuga laudantium tempora laborum dolore id ab provident ad aliquam repudiandae, nostrum dolores. Deleniti consectetur tempore accusantium iste ducimus nesciunt distinctio, inventore doloribus totam quam quasi, excepturi facere culpa quas officiis iure qui eos. Corrupti nostrum aut ipsam officia consequatur assumenda possimus. Totam ut natus deleniti dolores, adipisci, molestias sequi optio recusandae illum eaque cumque numquam animi velit quibusdam quo ea nesciunt reprehenderit? Quam enim tempora in. Fuga ex odit laudantium repellendus temporibus tempora, culpa, facere laboriosam dignissimos inventore sunt minima, non tempore. Atque nobis dolorem deleniti fugit, obcaecati odit placeat eaque esse aliquam qui sint ullam quisquam similique, perspiciatis nemo possimus neque repellat itaque minus ipsam! Consequatur vel laboriosam deserunt, possimus id veritatis non porro facilis nam impedit perferendis minus libero quam! Officia temporibus eius, asperiores earum ullam necessitatibus suscipit! Sint omnis culpa fugit esse dolores voluptates error, sed optio animi accusamus maxime, quos odit similique, alias ab rem odio inventore iste dolore sequi iusto. Ullam dolor aliquam quo, ab necessitatibus reiciendis vitae, beatae fuga iste modi saepe consectetur repellat quia error vel iure, qui asperiores tenetur atque! Autem delectus similique aliquam possimus rem. Mollitia quibusdam, totam harum necessitatibus aut accusamus amet quod doloribus natus, error blanditiis voluptates, cum rem ratione eveniet culpa unde animi! Cupiditate, harum quis autem atque aperiam doloremque, enim, aspernatur vero ea esse rerum eum. Odio laborum sequi aliquam amet rerum distinctio quaerat dicta, placeat aut repudiandae expedita ipsum quam consequatur architecto enim optio sint atque praesentium sunt sapiente ea unde! Quod qui maxime unde beatae quibusdam, eaque doloribus laborum tempore et! Ipsum vel perferendis voluptatum exercitationem, officia odit consequatur magni hic consectetur adipisci libero, eos aspernatur, nulla amet possimus eaque voluptate veniam cumque tempore?",
    ],
  },
  {
    title: "Warehouse management system (WMS)",
    description: "Systems for efficient management of warehouse operations and inventory.",
    image: Wms,
    content: [
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum suscipit, eos accusamus recusandae nemo voluptas consequuntur perspiciatis iusto obcaecati possimus temporibus quia doloribus voluptatem quas. Iusto nisi architecto, quibusdam dolor ipsum inventore ut alias atque! Nisi, iusto fuga ullam atque praesentium illum, sunt dolores minima quod laborum consequatur velit ipsa aliquid placeat! Laborum inventore recusandae aut a dolorem! Explicabo dolorem iusto exercitationem deserunt molestiae recusandae suscipit quae quaerat dolor inventore cumque delectus maxime consequatur sequi, temporibus nam aspernatur eum voluptas tenetur voluptate a natus impedit ea? Doloremque facilis reprehenderit distinctio labore libero aspernatur obcaecati velit iusto ipsa. Ea error atque, blanditiis ducimus possimus ipsam, similique aut qui earum expedita illum tenetur cumque laudantium cum dicta voluptatum optio. Modi illo amet pariatur omnis sapiente, laboriosam fugiat blanditiis labore laudantium quasi illum ratione suscipit, unde cumque accusantium animi dicta! Totam possimus accusantium minus vero illum suscipit reiciendis, cumque debitis quisquam placeat, ducimus, exercitationem harum quia quo pariatur quaerat voluptas dicta officiis ex est. Esse nihil obcaecati minima deleniti vel, dolore, maxime a quis ab reprehenderit ut illum, sapiente in! Nobis, autem quasi optio id illo facilis, fugit unde harum corporis dicta placeat! Quos nulla veniam saepe earum ratione maxime quasi magnam animi maiores? Ullam sequi, soluta eum dolorum possimus laudantium tempore, inventore dolor nemo quos, eligendi reiciendis labore magni! Voluptatem facere ratione rerum tempore labore suscipit itaque ipsum architecto eius! Possimus, minima odio. Nostrum quos eligendi, voluptate explicabo molestiae error aliquid obcaecati doloremque distinctio vel amet quam dignissimos officiis eum maiores saepe.",
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere velit totam doloremque? Atque accusamus hic non quidem eligendi deleniti ipsa fuga laudantium tempora laborum dolore id ab provident ad aliquam repudiandae, nostrum dolores. Deleniti consectetur tempore accusantium iste ducimus nesciunt distinctio, inventore doloribus totam quam quasi, excepturi facere culpa quas officiis iure qui eos. Corrupti nostrum aut ipsam officia consequatur assumenda possimus. Totam ut natus deleniti dolores, adipisci, molestias sequi optio recusandae illum eaque cumque numquam animi velit quibusdam quo ea nesciunt reprehenderit? Quam enim tempora in. Fuga ex odit laudantium repellendus temporibus tempora, culpa, facere laboriosam dignissimos inventore sunt minima, non tempore. Atque nobis dolorem deleniti fugit, obcaecati odit placeat eaque esse aliquam qui sint ullam quisquam similique, perspiciatis nemo possimus neque repellat itaque minus ipsam! Consequatur vel laboriosam deserunt, possimus id veritatis non porro facilis nam impedit perferendis minus libero quam! Officia temporibus eius, asperiores earum ullam necessitatibus suscipit! Sint omnis culpa fugit esse dolores voluptates error, sed optio animi accusamus maxime, quos odit similique, alias ab rem odio inventore iste dolore sequi iusto. Ullam dolor aliquam quo, ab necessitatibus reiciendis vitae, beatae fuga iste modi saepe consectetur repellat quia error vel iure, qui asperiores tenetur atque! Autem delectus similique aliquam possimus rem. Mollitia quibusdam, totam harum necessitatibus aut accusamus amet quod doloribus natus, error blanditiis voluptates, cum rem ratione eveniet culpa unde animi! Cupiditate, harum quis autem atque aperiam doloremque, enim, aspernatur vero ea esse rerum eum. Odio laborum sequi aliquam amet rerum distinctio quaerat dicta, placeat aut repudiandae expedita ipsum quam consequatur architecto enim optio sint atque praesentium sunt sapiente ea unde! Quod qui maxime unde beatae quibusdam, eaque doloribus laborum tempore et! Ipsum vel perferendis voluptatum exercitationem, officia odit consequatur magni hic consectetur adipisci libero, eos aspernatur, nulla amet possimus eaque voluptate veniam cumque tempore?",
    ],
  },
  {
    title: "Order management systems",
    description: "Efficient systems for processing and tracking orders across channels.",
    image: Order,
    content: [
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum suscipit, eos accusamus recusandae nemo voluptas consequuntur perspiciatis iusto obcaecati possimus temporibus quia doloribus voluptatem quas. Iusto nisi architecto, quibusdam dolor ipsum inventore ut alias atque! Nisi, iusto fuga ullam atque praesentium illum, sunt dolores minima quod laborum consequatur velit ipsa aliquid placeat! Laborum inventore recusandae aut a dolorem! Explicabo dolorem iusto exercitationem deserunt molestiae recusandae suscipit quae quaerat dolor inventore cumque delectus maxime consequatur sequi, temporibus nam aspernatur eum voluptas tenetur voluptate a natus impedit ea? Doloremque facilis reprehenderit distinctio labore libero aspernatur obcaecati velit iusto ipsa. Ea error atque, blanditiis ducimus possimus ipsam, similique aut qui earum expedita illum tenetur cumque laudantium cum dicta voluptatum optio. Modi illo amet pariatur omnis sapiente, laboriosam fugiat blanditiis labore laudantium quasi illum ratione suscipit, unde cumque accusantium animi dicta! Totam possimus accusantium minus vero illum suscipit reiciendis, cumque debitis quisquam placeat, ducimus, exercitationem harum quia quo pariatur quaerat voluptas dicta officiis ex est. Esse nihil obcaecati minima deleniti vel, dolore, maxime a quis ab reprehenderit ut illum, sapiente in! Nobis, autem quasi optio id illo facilis, fugit unde harum corporis dicta placeat! Quos nulla veniam saepe earum ratione maxime quasi magnam animi maiores? Ullam sequi, soluta eum dolorum possimus laudantium tempore, inventore dolor nemo quos, eligendi reiciendis labore magni! Voluptatem facere ratione rerum tempore labore suscipit itaque ipsum architecto eius! Possimus, minima odio. Nostrum quos eligendi, voluptate explicabo molestiae error aliquid obcaecati doloremque distinctio vel amet quam dignissimos officiis eum maiores saepe.",
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere velit totam doloremque? Atque accusamus hic non quidem eligendi deleniti ipsa fuga laudantium tempora laborum dolore id ab provident ad aliquam repudiandae, nostrum dolores. Deleniti consectetur tempore accusantium iste ducimus nesciunt distinctio, inventore doloribus totam quam quasi, excepturi facere culpa quas officiis iure qui eos. Corrupti nostrum aut ipsam officia consequatur assumenda possimus. Totam ut natus deleniti dolores, adipisci, molestias sequi optio recusandae illum eaque cumque numquam animi velit quibusdam quo ea nesciunt reprehenderit? Quam enim tempora in. Fuga ex odit laudantium repellendus temporibus tempora, culpa, facere laboriosam dignissimos inventore sunt minima, non tempore. Atque nobis dolorem deleniti fugit, obcaecati odit placeat eaque esse aliquam qui sint ullam quisquam similique, perspiciatis nemo possimus neque repellat itaque minus ipsam! Consequatur vel laboriosam deserunt, possimus id veritatis non porro facilis nam impedit perferendis minus libero quam! Officia temporibus eius, asperiores earum ullam necessitatibus suscipit! Sint omnis culpa fugit esse dolores voluptates error, sed optio animi accusamus maxime, quos odit similique, alias ab rem odio inventore iste dolore sequi iusto. Ullam dolor aliquam quo, ab necessitatibus reiciendis vitae, beatae fuga iste modi saepe consectetur repellat quia error vel iure, qui asperiores tenetur atque! Autem delectus similique aliquam possimus rem. Mollitia quibusdam, totam harum necessitatibus aut accusamus amet quod doloribus natus, error blanditiis voluptates, cum rem ratione eveniet culpa unde animi! Cupiditate, harum quis autem atque aperiam doloremque, enim, aspernatur vero ea esse rerum eum. Odio laborum sequi aliquam amet rerum distinctio quaerat dicta, placeat aut repudiandae expedita ipsum quam consequatur architecto enim optio sint atque praesentium sunt sapiente ea unde! Quod qui maxime unde beatae quibusdam, eaque doloribus laborum tempore et! Ipsum vel perferendis voluptatum exercitationem, officia odit consequatur magni hic consectetur adipisci libero, eos aspernatur, nulla amet possimus eaque voluptate veniam cumque tempore?",
    ],
  },
  {
    title: "Social media integration tools",
    description: "Tools for seamless management and engagement across social media channels.",
    image: Social,
    content: [
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum suscipit, eos accusamus recusandae nemo voluptas consequuntur perspiciatis iusto obcaecati possimus temporibus quia doloribus voluptatem quas. Iusto nisi architecto, quibusdam dolor ipsum inventore ut alias atque! Nisi, iusto fuga ullam atque praesentium illum, sunt dolores minima quod laborum consequatur velit ipsa aliquid placeat! Laborum inventore recusandae aut a dolorem! Explicabo dolorem iusto exercitationem deserunt molestiae recusandae suscipit quae quaerat dolor inventore cumque delectus maxime consequatur sequi, temporibus nam aspernatur eum voluptas tenetur voluptate a natus impedit ea? Doloremque facilis reprehenderit distinctio labore libero aspernatur obcaecati velit iusto ipsa. Ea error atque, blanditiis ducimus possimus ipsam, similique aut qui earum expedita illum tenetur cumque laudantium cum dicta voluptatum optio. Modi illo amet pariatur omnis sapiente, laboriosam fugiat blanditiis labore laudantium quasi illum ratione suscipit, unde cumque accusantium animi dicta! Totam possimus accusantium minus vero illum suscipit reiciendis, cumque debitis quisquam placeat, ducimus, exercitationem harum quia quo pariatur quaerat voluptas dicta officiis ex est. Esse nihil obcaecati minima deleniti vel, dolore, maxime a quis ab reprehenderit ut illum, sapiente in! Nobis, autem quasi optio id illo facilis, fugit unde harum corporis dicta placeat! Quos nulla veniam saepe earum ratione maxime quasi magnam animi maiores? Ullam sequi, soluta eum dolorum possimus laudantium tempore, inventore dolor nemo quos, eligendi reiciendis labore magni! Voluptatem facere ratione rerum tempore labore suscipit itaque ipsum architecto eius! Possimus, minima odio. Nostrum quos eligendi, voluptate explicabo molestiae error aliquid obcaecati doloremque distinctio vel amet quam dignissimos officiis eum maiores saepe.",
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere velit totam doloremque? Atque accusamus hic non quidem eligendi deleniti ipsa fuga laudantium tempora laborum dolore id ab provident ad aliquam repudiandae, nostrum dolores. Deleniti consectetur tempore accusantium iste ducimus nesciunt distinctio, inventore doloribus totam quam quasi, excepturi facere culpa quas officiis iure qui eos. Corrupti nostrum aut ipsam officia consequatur assumenda possimus. Totam ut natus deleniti dolores, adipisci, molestias sequi optio recusandae illum eaque cumque numquam animi velit quibusdam quo ea nesciunt reprehenderit? Quam enim tempora in. Fuga ex odit laudantium repellendus temporibus tempora, culpa, facere laboriosam dignissimos inventore sunt minima, non tempore. Atque nobis dolorem deleniti fugit, obcaecati odit placeat eaque esse aliquam qui sint ullam quisquam similique, perspiciatis nemo possimus neque repellat itaque minus ipsam! Consequatur vel laboriosam deserunt, possimus id veritatis non porro facilis nam impedit perferendis minus libero quam! Officia temporibus eius, asperiores earum ullam necessitatibus suscipit! Sint omnis culpa fugit esse dolores voluptates error, sed optio animi accusamus maxime, quos odit similique, alias ab rem odio inventore iste dolore sequi iusto. Ullam dolor aliquam quo, ab necessitatibus reiciendis vitae, beatae fuga iste modi saepe consectetur repellat quia error vel iure, qui asperiores tenetur atque! Autem delectus similique aliquam possimus rem. Mollitia quibusdam, totam harum necessitatibus aut accusamus amet quod doloribus natus, error blanditiis voluptates, cum rem ratione eveniet culpa unde animi! Cupiditate, harum quis autem atque aperiam doloremque, enim, aspernatur vero ea esse rerum eum. Odio laborum sequi aliquam amet rerum distinctio quaerat dicta, placeat aut repudiandae expedita ipsum quam consequatur architecto enim optio sint atque praesentium sunt sapiente ea unde! Quod qui maxime unde beatae quibusdam, eaque doloribus laborum tempore et! Ipsum vel perferendis voluptatum exercitationem, officia odit consequatur magni hic consectetur adipisci libero, eos aspernatur, nulla amet possimus eaque voluptate veniam cumque tempore?",
    ],
  },
  {
    title: "Product catalog management",
    description:
      "Tools for organizing and managing product catalogs, including product information and pricing.",
    image: Catalog,
    content: [
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum suscipit, eos accusamus recusandae nemo voluptas consequuntur perspiciatis iusto obcaecati possimus temporibus quia doloribus voluptatem quas. Iusto nisi architecto, quibusdam dolor ipsum inventore ut alias atque! Nisi, iusto fuga ullam atque praesentium illum, sunt dolores minima quod laborum consequatur velit ipsa aliquid placeat! Laborum inventore recusandae aut a dolorem! Explicabo dolorem iusto exercitationem deserunt molestiae recusandae suscipit quae quaerat dolor inventore cumque delectus maxime consequatur sequi, temporibus nam aspernatur eum voluptas tenetur voluptate a natus impedit ea? Doloremque facilis reprehenderit distinctio labore libero aspernatur obcaecati velit iusto ipsa. Ea error atque, blanditiis ducimus possimus ipsam, similique aut qui earum expedita illum tenetur cumque laudantium cum dicta voluptatum optio. Modi illo amet pariatur omnis sapiente, laboriosam fugiat blanditiis labore laudantium quasi illum ratione suscipit, unde cumque accusantium animi dicta! Totam possimus accusantium minus vero illum suscipit reiciendis, cumque debitis quisquam placeat, ducimus, exercitationem harum quia quo pariatur quaerat voluptas dicta officiis ex est. Esse nihil obcaecati minima deleniti vel, dolore, maxime a quis ab reprehenderit ut illum, sapiente in! Nobis, autem quasi optio id illo facilis, fugit unde harum corporis dicta placeat! Quos nulla veniam saepe earum ratione maxime quasi magnam animi maiores? Ullam sequi, soluta eum dolorum possimus laudantium tempore, inventore dolor nemo quos, eligendi reiciendis labore magni! Voluptatem facere ratione rerum tempore labore suscipit itaque ipsum architecto eius! Possimus, minima odio. Nostrum quos eligendi, voluptate explicabo molestiae error aliquid obcaecati doloremque distinctio vel amet quam dignissimos officiis eum maiores saepe.",
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere velit totam doloremque? Atque accusamus hic non quidem eligendi deleniti ipsa fuga laudantium tempora laborum dolore id ab provident ad aliquam repudiandae, nostrum dolores. Deleniti consectetur tempore accusantium iste ducimus nesciunt distinctio, inventore doloribus totam quam quasi, excepturi facere culpa quas officiis iure qui eos. Corrupti nostrum aut ipsam officia consequatur assumenda possimus. Totam ut natus deleniti dolores, adipisci, molestias sequi optio recusandae illum eaque cumque numquam animi velit quibusdam quo ea nesciunt reprehenderit? Quam enim tempora in. Fuga ex odit laudantium repellendus temporibus tempora, culpa, facere laboriosam dignissimos inventore sunt minima, non tempore. Atque nobis dolorem deleniti fugit, obcaecati odit placeat eaque esse aliquam qui sint ullam quisquam similique, perspiciatis nemo possimus neque repellat itaque minus ipsam! Consequatur vel laboriosam deserunt, possimus id veritatis non porro facilis nam impedit perferendis minus libero quam! Officia temporibus eius, asperiores earum ullam necessitatibus suscipit! Sint omnis culpa fugit esse dolores voluptates error, sed optio animi accusamus maxime, quos odit similique, alias ab rem odio inventore iste dolore sequi iusto. Ullam dolor aliquam quo, ab necessitatibus reiciendis vitae, beatae fuga iste modi saepe consectetur repellat quia error vel iure, qui asperiores tenetur atque! Autem delectus similique aliquam possimus rem. Mollitia quibusdam, totam harum necessitatibus aut accusamus amet quod doloribus natus, error blanditiis voluptates, cum rem ratione eveniet culpa unde animi! Cupiditate, harum quis autem atque aperiam doloremque, enim, aspernatur vero ea esse rerum eum. Odio laborum sequi aliquam amet rerum distinctio quaerat dicta, placeat aut repudiandae expedita ipsum quam consequatur architecto enim optio sint atque praesentium sunt sapiente ea unde! Quod qui maxime unde beatae quibusdam, eaque doloribus laborum tempore et! Ipsum vel perferendis voluptatum exercitationem, officia odit consequatur magni hic consectetur adipisci libero, eos aspernatur, nulla amet possimus eaque voluptate veniam cumque tempore?",
    ],
  },
  {
    title: "Analytics and reporting platforms",
    description:
      "Tools for analyzing customer behavior, sales performance, and channel effectiveness.",
    image: Report,
    content: [
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum suscipit, eos accusamus recusandae nemo voluptas consequuntur perspiciatis iusto obcaecati possimus temporibus quia doloribus voluptatem quas. Iusto nisi architecto, quibusdam dolor ipsum inventore ut alias atque! Nisi, iusto fuga ullam atque praesentium illum, sunt dolores minima quod laborum consequatur velit ipsa aliquid placeat! Laborum inventore recusandae aut a dolorem! Explicabo dolorem iusto exercitationem deserunt molestiae recusandae suscipit quae quaerat dolor inventore cumque delectus maxime consequatur sequi, temporibus nam aspernatur eum voluptas tenetur voluptate a natus impedit ea? Doloremque facilis reprehenderit distinctio labore libero aspernatur obcaecati velit iusto ipsa. Ea error atque, blanditiis ducimus possimus ipsam, similique aut qui earum expedita illum tenetur cumque laudantium cum dicta voluptatum optio. Modi illo amet pariatur omnis sapiente, laboriosam fugiat blanditiis labore laudantium quasi illum ratione suscipit, unde cumque accusantium animi dicta! Totam possimus accusantium minus vero illum suscipit reiciendis, cumque debitis quisquam placeat, ducimus, exercitationem harum quia quo pariatur quaerat voluptas dicta officiis ex est. Esse nihil obcaecati minima deleniti vel, dolore, maxime a quis ab reprehenderit ut illum, sapiente in! Nobis, autem quasi optio id illo facilis, fugit unde harum corporis dicta placeat! Quos nulla veniam saepe earum ratione maxime quasi magnam animi maiores? Ullam sequi, soluta eum dolorum possimus laudantium tempore, inventore dolor nemo quos, eligendi reiciendis labore magni! Voluptatem facere ratione rerum tempore labore suscipit itaque ipsum architecto eius! Possimus, minima odio. Nostrum quos eligendi, voluptate explicabo molestiae error aliquid obcaecati doloremque distinctio vel amet quam dignissimos officiis eum maiores saepe.",
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere velit totam doloremque? Atque accusamus hic non quidem eligendi deleniti ipsa fuga laudantium tempora laborum dolore id ab provident ad aliquam repudiandae, nostrum dolores. Deleniti consectetur tempore accusantium iste ducimus nesciunt distinctio, inventore doloribus totam quam quasi, excepturi facere culpa quas officiis iure qui eos. Corrupti nostrum aut ipsam officia consequatur assumenda possimus. Totam ut natus deleniti dolores, adipisci, molestias sequi optio recusandae illum eaque cumque numquam animi velit quibusdam quo ea nesciunt reprehenderit? Quam enim tempora in. Fuga ex odit laudantium repellendus temporibus tempora, culpa, facere laboriosam dignissimos inventore sunt minima, non tempore. Atque nobis dolorem deleniti fugit, obcaecati odit placeat eaque esse aliquam qui sint ullam quisquam similique, perspiciatis nemo possimus neque repellat itaque minus ipsam! Consequatur vel laboriosam deserunt, possimus id veritatis non porro facilis nam impedit perferendis minus libero quam! Officia temporibus eius, asperiores earum ullam necessitatibus suscipit! Sint omnis culpa fugit esse dolores voluptates error, sed optio animi accusamus maxime, quos odit similique, alias ab rem odio inventore iste dolore sequi iusto. Ullam dolor aliquam quo, ab necessitatibus reiciendis vitae, beatae fuga iste modi saepe consectetur repellat quia error vel iure, qui asperiores tenetur atque! Autem delectus similique aliquam possimus rem. Mollitia quibusdam, totam harum necessitatibus aut accusamus amet quod doloribus natus, error blanditiis voluptates, cum rem ratione eveniet culpa unde animi! Cupiditate, harum quis autem atque aperiam doloremque, enim, aspernatur vero ea esse rerum eum. Odio laborum sequi aliquam amet rerum distinctio quaerat dicta, placeat aut repudiandae expedita ipsum quam consequatur architecto enim optio sint atque praesentium sunt sapiente ea unde! Quod qui maxime unde beatae quibusdam, eaque doloribus laborum tempore et! Ipsum vel perferendis voluptatum exercitationem, officia odit consequatur magni hic consectetur adipisci libero, eos aspernatur, nulla amet possimus eaque voluptate veniam cumque tempore?",
    ],
  },
];

const DetailArticle = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("md"));

  const articleId = parseInt(id || "");

  React.useEffect(() => {
    if (articleId == null) {
      return navigate(-1);
    }
  });

  return (
    <div id="detail-article">
      <Container sx={{ mt: "3rem" }}>
        <Box display="flex" flexDirection="column">
          <Typography
            variant="h3"
            gutterBottom
            sx={{
              fontWeight: 700,
              fontFamily: '"gilroy-bold", sans-serif',
            }}>
            {omnichannelProducts[articleId]?.title}
          </Typography>
          <Typography
            color="inherit"
            variant="h6"
            mt={"1rem"}
            component={"p"}
            sx={{
              fontWeight: 500,
              fontFamily: '"gilroy-bold", sans-serif',
            }}>
            {omnichannelProducts[articleId]?.description}
          </Typography>
        </Box>
        <Box display="flex" flexDirection="column" mt={"3rem"}>
          <img src={omnichannelProducts[articleId]?.image} alt="Dont know" />
        </Box>
        <Box display="flex" flexDirection="column">
          {omnichannelProducts[articleId]?.content.map((x) => (
            <Typography
              color="inherit"
              variant="body1"
              mt={"1rem"}
              component={"p"}
              sx={{
                fontWeight: 500,
                fontFamily: '"gilroy-bold", sans-serif',
                textIndent: "30px",
              }}>
              {x}
            </Typography>
          ))}
        </Box>
      </Container>
    </div>
  );
};

export default DetailArticle;
